added ambient-link ability pack
symfony/recipes-contrib pull request #1016
Opened 2020-10-04 10:30 UTC by robinlehrmann

| Q             | A
| ------------- | ---
| License       | MIT

Added ambient.link ability pack.

2020-10-11 07:24 UTC, Nyholm commented
Thank you for this PR. 

Im not sure why you create a "pack"? Why just not create a recipe for `ambient-link/ability-sdk`?

2020-10-13 12:27 UTC, robinlehrmann commented
> Thank you for this PR.
> 
> Im not sure why you create a "pack"? Why just not create a recipe for `ambient-link/ability-sdk`?

You are right. I changed the name and removed the pack

2020-10-26 13:54 UTC, Nyholm commented on ambient-link/ability-sdk/1.0/config/packages/ability.yaml
> +ability:
This line and below can be removed.

2020-10-26 13:55 UTC, Nyholm commented on ambient-link/ability-sdk/1.0/config/packages/ability.yaml
> +        arguments: ['@ambient_link.connection_settings', '%env(AMBIENT_LINK_USERNAME)%', '%env(AMBIENT_LINK_PASSWORD)%']
Dont forget to defined a service for `ambient_link.connection_settings`

2020-10-26 15:49 UTC, Nyholm requested changes
Thank you

2020-10-26 15:49 UTC, Nyholm commented on ambient-link/ability-sdk/1.0/config/packages/ability.yaml
> +#                    to: notInAnyRoom
I suggest removing lines 20 to 51. They dont help the user

2020-10-26 15:49 UTC, Nyholm commented on ambient-link/ability-sdk/1.0/src/AbilityEventSubscriber.php
> +final class AbilityEventSubscriber implements Ability
Is this class really needed? 

I think it can be removed.

2020-10-26 16:15 UTC, Nyholm requested changes
Thank you. 

Can you make sure that you define all environment variables? Also, dont define more environment variables than you are using.

2020-10-26 16:15 UTC, Nyholm commented on ambient-link/ability-sdk/1.0/manifest.json
> +        "AMBIENT_LINK_BASE_TOPIC": "",
This is not used

2020-10-26 16:15 UTC, Nyholm commented on ambient-link/ability-sdk/1.0/manifest.json
> +        "AMBIENT_LINK_ABILITY_TOKEN": "",
This is not used

2020-10-26 16:15 UTC, Nyholm commented on ambient-link/ability-sdk/1.0/manifest.json
> +        "AMBIENT_LINK_MQTT_USERNAME_AND_PASSWORD": "",
This is not used

2020-10-26 16:15 UTC, Nyholm commented on ambient-link/ability-sdk/1.0/manifest.json
> +        "AMBIENT_LINK_MQTT_URL": "${MQTT_USERNAME_AND_PASSWORD}${MQTT_HOST}:1883"
This is not used

2020-10-26 16:15 UTC, Nyholm commented on ambient-link/ability-sdk/1.0/config/packages/ability.yaml
> +        arguments: ['@amnient.link_connection_settings', '%env(AMBIENT_LINK_USERNAME)%', '%env(AMBIENT_LINK_PASSWORD)%']
There is no definition for `AMBIENT_LINK_USERNAME` or `AMBIENT_LINK_PASSWORD`

2020-10-27 16:20 UTC, Nyholm approved these changes
Thank you.

2020-10-27 16:20 UTC, merged