Add recipe for player259/graphql-bundle
symfony/recipes-contrib pull request #1037
Opened 2020-11-16 19:29 UTC by player259

| Q             | A
| ------------- | ---
| License       | MIT

Add recipe for player259/graphql-bundle

2020-12-01 14:22 UTC, OskarStark commented on player259/graphql-bundle/1.0/config/routes/player259_graphql.yaml
> +# To assign endpoint to specific url
```suggestion
# To assign an endpoint to a specific url
```

2021-08-02 04:33 UTC, Nyholm requested changes
Please rebase your PR so we get the new CI jobs.

2021-08-02 04:33 UTC, Nyholm commented on player259/graphql-bundle/1.0/config/packages/player259_graphql.yaml
> +#    logger: '?logger'
This file is not needed.

2021-08-02 04:33 UTC, Nyholm commented on player259/graphql-bundle/1.0/config/routes/player259_graphql.yaml
> +#player259_graphql_index:
This is documentation. Let's remove it from the route configuration.

2021-08-02 18:00 UTC, Nyholm approved these changes
Awesome. Thank you

2021-08-02 18:00 UTC, merged