Amorvan responders bundle
symfony/recipes-contrib pull request #1109
Opened 2021-03-17 14:45 UTC by AurelienMo

| Q             | A
| ------------- | ---
| License       | MIT

For reference:
[https://github.com/AurelienMo/RespondersBundle](https://github.com/AurelienMo/RespondersBundle)

2021-03-17 15:36 UTC, OskarStark commented
![CleanShot 2021-03-17 at 16 35 39](https://user-images.githubusercontent.com/995707/111494497-d1a67000-873e-11eb-8158-262fc5d5bf52.png)

It looks like your email address is not associated with your Github Account

2021-03-17 15:51 UTC, AurelienMo commented
@OskarStark Failed on build travis, I don't understand why. If I create a project on local environment (same process as Travis), no errors occured :(

2021-03-17 15:57 UTC, AurelienMo commented
> ![CleanShot 2021-03-17 at 16 35 39](https://user-images.githubusercontent.com/995707/111494497-d1a67000-873e-11eb-8158-262fc5d5bf52.png)
> 
> It looks like your email address is not associated with your Github Account

It's ok

2021-03-17 20:20 UTC, AurelienMo commented
@OskarStark CI travis ok :+1:

2021-04-19 15:06 UTC, Nyholm requested changes

2021-04-19 15:06 UTC, Nyholm commented on amorvan/responders-bundle/4.0/config/packages/amorvan_responders_bundle.yaml
> +    Morvan\Bundle\RespondersBundle\Responders: null
You bundle should register these services in https://github.com/AurelienMo/RespondersBundle/blob/development/Resources/config/services.xml

You dont need a recipe =) 
Things will work anyways.

2021-04-19 15:06 UTC, closed without merging