add new bundle ecoco/sylius-base-price-plugin
symfony/recipes-contrib pull request #1146
Opened 2021-05-10 12:52 UTC by andrejsstepanovs

| Q             | A
| ------------- | ---
| License       | MIT

2021-05-11 10:23 UTC, andrejsstepanovs commented
If I do proceed to fix Travis CI build then I will just break my recipe. Because I will need to enable and configure so many unrelated bundles. This will definitely be destructing for many sylius shops that oped to not use them.

I tried recipe using [given instructions](1) and it works exactly as expected.
Not sure what I can do to get this thing merged automatically. Any pointers are welcomed.

[1]: https://flex.symfony.com/r/github.com/symfony/recipes-contrib/1146

2021-06-23 08:50 UTC, andrejsstepanovs commented
Can this be checked and accepted by human being please?

2021-08-02 05:08 UTC, Nyholm commented
The CI jobs are not really happy. 

Could you rebase this PR to make sure the updated CI jobs are green?
I need it to work on Symfony 4 or 5.

2022-02-19 10:54 UTC, Nyholm commented
Hey. Dont forget about this PR.

2022-03-09 15:18 UTC, vvasiloi requested changes
Hey @andrejsstepanovs, if you still want this merged, please rebase the branch and make the requested changes.

2022-03-09 15:18 UTC, vvasiloi commented on ecoco/sylius-base-price-plugin/1.2/manifest.json
> +    "copy-from-package": {
Please add the files to the recipe and use `copy-from-recipe` instead.

2022-12-15 07:28 UTC, fabpot commented
Closing as there is no more activity and the PR cannot be merged as is. Feel free to reopen if you like.

2022-12-15 07:28 UTC, closed without merging