Symfony Flex Recipe for Woleet-Bundle
symfony/recipes-contrib pull request #1183
Opened 2021-07-23 10:04 UTC by germainlecourtoissloop

| Q             | A
| ------------- | ---
| License       | MIT

2021-08-02 17:55 UTC, Nyholm requested changes
Thank you. Just a minor thing

2021-08-02 17:55 UTC, Nyholm commented on monsieursloop/woleet-bundle/1.0/config/packages/monsieur_sloop_woleet.yaml
> +    #api_url: "https://custiom.api.woleet.io"
This is not needed in the recipe. Add a link to your documentation instead.

2021-08-02 20:26 UTC, germainlecourtoissloop commented
Done @Nyholm  :)

2021-08-03 00:51 UTC, Nyholm approved these changes
Thank you

2021-08-03 00:51 UTC, merged