Add recipe for phpsword/sword-bundle
symfony/recipes-contrib pull request #1433
Opened 2022-09-08 05:04 UTC by williarin

| Q             | A
| ------------- | ---
| License       | MIT
| Packagist     | https://packagist.org/packages/phpsword/sword-bundle

Recipe for [phpsword/sword-bundle](https://github.com/phpsword/sword-bundle).

2022-12-15 07:05 UTC, fabpot requested changes

2022-12-15 07:05 UTC, fabpot commented on phpsword/sword-bundle/1.0/manifest.json
> +        "install/bin/console": "%BIN_DIR%/console",
That would override Symfony's own console script. That's a no go IMHO.

2022-12-15 07:05 UTC, fabpot commented on phpsword/sword-bundle/1.0/manifest.json
> +        "install/docker-compose.prod.yml": "docker-compose.prod.yml",
We have a specific mechanism to add entries in Docker files that should be used instead (to avoid overriding the ones from Symfony).

2022-12-30 09:35 UTC, fabpot commented
Closing for now. Feel free to reopen when/if you have time to finish this PR. Thank you.

2022-12-30 09:35 UTC, closed without merging

2022-12-30 13:59 UTC, williarin commented
Hi, really sorry I didn't notice the review! I've made the changes in my branch to remove the problematic files from the recipe manifest.
Could the PR be reopened?

2022-12-30 16:41 UTC, fabpot commented
@williarin I think you're the only one able to reopen it. If not, can you just submit a new one?