adding recipe for codeception 5.0
symfony/recipes-contrib pull request #1435
Opened 2022-09-16 12:32 UTC by adrianmare

| Q             | A
| ------------- | ---
| License       | MIT
| Packagist     |

2022-12-17 17:57 UTC, OskarStark commented on codeception/codeception/5.0/tests/Acceptance.suite.yaml
> +step_decorators: null
Indention looks wrong, it's not the same like in the next file in this PR

2022-12-30 12:49 UTC, fabpot requested changes
I would remove all PHP classes, which should not be part of a recipe.

2022-12-30 12:51 UTC, fabpot commented
Duplicate work happening in #1432

2023-01-08 10:50 UTC, fabpot commented
Closing in favor of #1432

2023-01-08 10:50 UTC, closed without merging