initial version for survos/bunny-bundle
symfony/recipes-contrib pull request #1711
Opened 2024-11-18 13:46 UTC by tacman

| Q             | A
| ------------- | ---
| License       | MIT
| Packagist     | https://packagist.org/packages/survos/bunny-bundle

2024-11-19 16:13 UTC, fabpot requested changes

2024-11-19 16:13 UTC, fabpot commented on survos/bunny-bundle/1.5/post-install.txt
> +
Maybe we only need 1 whiteline?

2024-11-19 16:13 UTC, fabpot commented on survos/bunny-bundle/1.5/config/packages/survos_bunny.yaml
> +    storage_zone:
```suggestion
    #storage_zone:
```

And maybe add a hint at what you're expecting here like:

```suggestion
    #storage_zone: something
```

2024-12-05 11:10 UTC, diimpp commented on survos/bunny-bundle/1.5/post-install.txt
> +
```suggestion
```

2025-01-29 07:52 UTC, fabpot approved these changes

2025-01-29 07:53 UTC, merged