fix: default invalid key
symfony/recipes-contrib pull request #1719
Opened 2024-12-04 09:33 UTC by martingold

| Q             | A
| ------------- | ---
| License       | MIT
| Packagist     |  https://packagist.org/packages/fluffydiscord/roadrunner-symfony-bundle

2024-12-05 10:53 UTC, diimpp requested changes
Hi @martingold , `http` part cannot be on top, so I assume it should be the other way around.

![image](https://github.com/user-attachments/assets/f1c00851-e3dc-4fc0-841d-8dad6ade9a9b)

2024-12-05 10:53 UTC, diimpp commented on fluffydiscord/roadrunner-symfony-bundle/3.0/config/packages/fluffy_discord_road_runner.yaml
> +            early_router_initialization: false
```suggestion
    fluffy_discord_road_runner:
        http:
            early_router_initialization: false
```

2024-12-05 15:09 UTC, martingold commented
You are correct, fixed. Thanks!

2024-12-06 14:24 UTC, fabpot approved these changes

2024-12-06 14:26 UTC, merged