add wickedone/phrase-tag-bundle
symfony/recipes-contrib pull request #1733
Opened 2024-12-20 09:47 UTC by wickedOne

| Q             | A
| ------------- | ---
| License       | MIT
| Packagist     | [wickedone/phrase-tag-bundle](https://packagist.org/packages/wickedone/phrase-tag-bundle)

2024-12-23 20:39 UTC, fabpot commented
Can you remove unrelated changes?

2024-12-23 23:54 UTC, diimpp requested changes
Please remove unrelated changes as Fabian mentioned.

2024-12-23 23:54 UTC, diimpp commented on wickedone/phrase-tag-bundle/2.0/manifest.json
> +    }
Just a suggestion, you can offer to configure DSN as well.
![image](https://github.com/user-attachments/assets/afbb5e67-9ede-4d3a-8b1c-16f4ad2d226d)

```suggestion
    "copy-from-recipe": {
        "config/": "%CONFIG_DIR%/"
    },
    "env": {
        "PHRASE_DSN": "phrase://PROJECT_ID:API_TOKEN@default?userAgent=myProject"
    }
```

2024-12-24 11:58 UTC, wickedOne commented
- removed unrelated changes (sorry, no idea how they managed to get in there)
- implemented `PHRASE_DSN` env var as suggested by @diimpp

2024-12-24 15:32 UTC, diimpp commented on wickedone/phrase-tag-bundle/2.0/config/packages/wickedone.yaml
Missed it at first, file name should follow bundle name,

```patch
--- wickedone.yaml
+++ wicked_one_phrase_tag.yaml
```

2024-12-24 17:32 UTC, wickedOne commented on wickedone/phrase-tag-bundle/2.0/config/packages/wickedone.yaml
done

2024-12-24 18:56 UTC, diimpp approved these changes

2024-12-24 18:56 UTC, merged